trigger:
  branches:
    include:
    - main
 

  paths:
    include:
    - 'notebooks/*'
    exclude:
    - 'azure-pipelines.yml'

pool:
  vmImage: 'windows-latest'

#########################
#BUILD STAGE FOR ADB
#########################

stages:
  - stage: ADB_Build
    displayName: Building Databricks Notebook Artifact
    jobs:
      - job: Creating
        displayName: "Creating Artifact"
        steps:
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/notebooks'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
            displayName: 'Copy Databricks Notebooks to Artifact Staging Directory'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifact: 'databricks'
              publishLocation: 'pipeline'
            displayName: 'Publish Artifacts: databricks'
  
  - stage: ADB_Release
    dependsOn: ADB_Build
    condition: succeeded('ADB_Build')
    displayName: Deploying Databricks Notebook in Dev
    jobs:
      - job: Deploying
        displayName: 'Deploying the Notebooks'
        steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            targetPath: '$(System.DefaultWorkingDirectory)'
          displayName: 'Download Build Artifact'
        - powershell: |
            tree "$(System.DefaultWorkingDirectory)" /F
          displayName: 'Treeview of System.DefaultWorkingDirectory'
        - task: configuredatabricks@0
          inputs:
            url: 'https://adb-3956781089307435.15.azuredatabricks.net/'
            token: 'dapi6d79968d8b499dba5a52df0121b103f0-3'
        - task: deploynotebooks@0
          inputs:
            notebooksFolderPath: '$(System.DefaultWorkingDirectory)/databricks'
            workspaceFolder: '/DataEngineering'