print("hello cmd")
print("Hello kapil varshney")
print("hello nagarro")
print("hello rahul")
print("hello mohit")
print("hello jack")
print("hello mack")
print("hey sonal gupta.....!!!!!!!!!!!!!")
print("heyyyyy sanjol")
print("hey shallu")
print("hello moto")
print("hello mbusa")
print("hello rahul")
print("hello rohan")
print("jaipur")
print("rajasthan")
